---
Name: zauberfisch-page-builder-draft-editor
After:
  - '#zauberfisch-page-builder'
---
zauberfisch\PageBuilder\PageBuilderField:
  css:
    - "zauberfisch/silverstripe-page-builder-draft-editor: client/dist/styles/bundle.css"
  javascript:
    - "zauberfisch/silverstripe-page-builder-draft-editor: client/dist/js/bundle.js"
  lang:
    - "zauberfisch/silverstripe-page-builder-draft-editor: client/lang"
